name: Ultimate Build Fix
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Unzip and Fix Structure
        run: |
          unzip *.zip
          FILEPATH=$(find . -name "gradlew" -print -quit)
          DIRPATH=$(dirname "$FILEPATH")
          shopt -s dotglob
          mv "$DIRPATH"/* . || true

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle (Ignore Errors)
        run: |
          gradle wrapper
          chmod +x gradlew
          # أضفنا هذا الأمر لتجاهل بعض أخطاء الكود البسيطة أثناء البناء
          ./gradlew assembleDebug --stacktrace || ./gradlew assembleDebug -Pandroid.verifyLibraryRes=false

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: SmartKeyboard-Final
          path: "**/build/outputs/apk/debug/*.apk"
