name: Build Sarmad Keyboard
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract Project
        run: |
          unzip Sarmad*.zip
          FILEPATH=$(find . -name "gradlew" -print -quit)
          DIRPATH=$(dirname "$FILEPATH")
          shopt -s dotglob
          mv "$DIRPATH"/* . || true

      - name: Fix Repository Error
        run: |
          # هذا الأمر سيحذف السطر المسبب للخطأ في ملف build.gradle تلقائياً
          sed -i '/google()/d' build.gradle || true
          sed -i '/mavenCentral()/d' build.gradle || true

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build APK
        run: |
          if [ ! -f "gradlew" ]; then gradle wrapper; fi
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Sarmad-Keyboard-Final
          path: "**/build/outputs/apk/debug/*.apk"
